// This file was generated by the Dreamlab editor.
// Entities tagged with 'editor/doNotSave' have not been persisted.

/* eslint-disable unicorn/no-abusive-eslint-disable */
/* eslint-disable */

import type { LooseSpawnableDefinition } from "@dreamlab.gg/core"

// prettier-ignore
export const level: LooseSpawnableDefinition[] = [
  {
    "entity": "@cvz/EnvironmentParticle",
    "args": {
      "width": 2939.76,
      "height": 128.15,
      "spriteSource": [
        {
          "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/dirt_03-removebg-preview-1710266327592.png"
        }
      ],
      "lifetime": {
        "min": 2,
        "max": 4
      },
      "frequency": 0.1,
      "emitterLifetime": -1,
      "spawnChance": 0.4,
      "particlesPerWave": 1,
      "maxParticles": 50,
      "alpha": {
        "start": 0.7,
        "end": 0
      },
      "scale": {
        "start": 0.05,
        "end": 0.3
      },
      "rotation": {
        "min": 0,
        "max": 360
      },
      "color": {
        "start": "#776649",
        "mid": "#8A7756",
        "end": "#B2996E"
      },
      "path": "sin(x/10) * 5",
      "speedList": [
        {
          "value": 10,
          "time": 0
        },
        {
          "value": 100,
          "time": 0.25
        },
        {
          "value": 0,
          "time": 1
        }
      ],
      "minMult": 0.8
    },
    "transform": {
      "position": {
        "x": -10253.231377072707,
        "y": 676.4255796566591
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "h6iaft9kkk3l4bwvpdswre1w",
    "tags": []
  },
  {
    "entity": "@cvz/HealItem",
    "args": {
      "width": 269.78,
      "height": 267.26,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/artboard_4_4x-removebg-preview-1710280303298.png"
      },
      "healAmount": 10
    },
    "transform": {
      "position": {
        "x": -3663.8178713982934,
        "y": 296.6220983902956
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "kwzk9haipees4zq81ac060a2",
    "tags": []
  },
  {
    "entity": "@cvz/InventoryItem",
    "args": {
      "width": 209.43,
      "height": 239.61,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bow-1702293278974.png"
      },
      "displayName": "Sam's Golden Bow",
      "animationName": "bow",
      "cost": 100,
      "damage": 5,
      "range": 1,
      "lore": "Once wielded by 'Sharp-Eye' Sam, the fastest archer in the West, this bow's arrows are said to whistle with the winds of the prairie and never miss a zombie's heart.",
      "bone": "handRight",
      "anchorX": 0.5,
      "anchorY": 0.5,
      "rotation": 0,
      "speedMultiplier": 1
    },
    "transform": {
      "position": {
        "x": -7877.052501613052,
        "y": 223.74721190707567
      },
      "rotation": 0,
      "zIndex": 9
    },
    "uid": "hed17ymwbvrywm2ib5ei7pf4",
    "tags": []
  },
  {
    "entity": "@cvz/InventoryItem",
    "args": {
      "width": 205.43,
      "height": 244.98,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/western_bow-1710275106977-removebg-preview-1710275206228.png"
      },
      "displayName": "Prairie String",
      "animationName": "bow",
      "cost": 100,
      "damage": 2,
      "range": 1,
      "lore": "A humble bow made from twisted mustang hair and gnarled wood. A silent guardian for any cowboy starting their battle against the undead.",
      "bone": "handRight",
      "anchorX": 0.5,
      "anchorY": 0.5,
      "rotation": 0,
      "speedMultiplier": 1
    },
    "transform": {
      "position": {
        "x": -8248.653046526664,
        "y": 227.88707846743966
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "pg5i5z0syt0plftn2gj6sx2a",
    "tags": []
  },
  {
    "entity": "@cvz/InventoryItem",
    "args": {
      "width": 188.97,
      "height": 196.81,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/1699656237486-1709318782244.png"
      },
      "displayName": "Burst Revolver",
      "animationName": "shoot",
      "cost": 100,
      "damage": 1,
      "range": 1,
      "lore": "Crafted by the legendary gunsmith 'Bullseye' Betty, this revolver's rapid bursts made it a favorite among cowboys holding the line in the great zombie sieges of the Old West.",
      "bone": "handRight",
      "anchorX": 0.5,
      "anchorY": 0.5,
      "rotation": 0,
      "speedMultiplier": 1
    },
    "transform": {
      "position": {
        "x": -7327.783903813832,
        "y": 233.7094371157773
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "roj8unub96rgub10seatzf8i",
    "tags": []
  },
  {
    "entity": "@cvz/MessageTrigger",
    "args": {
      "width": 348.64,
      "height": 484.2,
      "message": " Howdy Partner! I reckon your cart's taken a bit of a tumble. No cause for concern, though. Our welcoming town's got your back, offering you a safe haven till we get that wagon of yours up and running again. Safe travels, Sheriff Stone"
    },
    "transform": {
      "position": {
        "x": -10093.783619713904,
        "y": 376.86544888504443
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "snp2e6qrphqmdwlo9t3tinxu",
    "tags": []
  },
  {
    "entity": "@cvz/MessageTrigger",
    "args": {
      "width": 593.1,
      "height": 507.87,
      "message": "\"I can't leave town until I get my wagon fixed\""
    },
    "transform": {
      "position": {
        "x": -12017.060814640443,
        "y": 304.47226746775976
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "adw2bqdw4fzmq7l8g1q2rauj",
    "tags": []
  },
  {
    "entity": "@cvz/MessageTrigger",
    "args": {
      "width": 371.06,
      "height": 480.96,
      "message": "Howdy! Jeb's the name, crafting weapons is my game. You look new here. Swing by and check out my arsenal for sale!"
    },
    "transform": {
      "position": {
        "x": -8748.704650653115,
        "y": 356.0642005632467
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ml8vuy5t3ouwlntxagw5nwxg",
    "tags": []
  },
  {
    "entity": "@cvz/MessageTrigger",
    "args": {
      "width": 217.09,
      "height": 387.62,
      "message": "Hey there! Did you hear? A big storm just rolled in right over the saloon!"
    },
    "transform": {
      "position": {
        "x": -5110.564446017372,
        "y": 381.1800040448913
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "qg75pl41sr2dmcvv9hlc2tae",
    "tags": []
  },
  {
    "entity": "@cvz/MessageTrigger",
    "args": {
      "width": 244.88,
      "height": 351.41,
      "message": "Beyond here, the town's in quite a disarray."
    },
    "transform": {
      "position": {
        "x": -1529.923802625487,
        "y": 375.2727165023797
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "hphr0f8hvko6kxtpte2o32n7",
    "tags": []
  },
  {
    "entity": "@cvz/MessageTrigger",
    "args": {
      "width": 239.39,
      "height": 276.4,
      "message": "Healing potions for sale! 🌿💖 Perfect for adventures. Grab yours now!"
    },
    "transform": {
      "position": {
        "x": -4041.8953414963175,
        "y": 300.26299492228316
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "gncm91i0ggc8cfxwgjgptebg",
    "tags": []
  },
  {
    "entity": "@cvz/MessageTrigger",
    "args": {
      "width": 199.1,
      "height": 189.07,
      "message": "Jackson didn't 'Shift' away from danger. A swift dash could've spared him this plot. ⚡️"
    },
    "transform": {
      "position": {
        "x": 353.23791514437784,
        "y": 514.8516546230117
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ho9mug65e649ff2poa761wx5",
    "tags": []
  },
  {
    "entity": "@dreamlab/BackgroundTrigger",
    "args": {
      "width": 28881.511852279044,
      "height": 3684.6319024790246,
      "onEnter": {
        "action": "set",
        "textureURL": "https://s3-assets.dreamlab.gg/uploaded-from-editor/sky2XY-1703001940523.png"
      },
      "onLeave": {
        "action": "clear"
      }
    },
    "transform": {
      "position": {
        "x": 759.8093749792733,
        "y": 292.56148232688884
      },
      "rotation": 0,
      "zIndex": -100
    },
    "uid": "d6yo1be0iq3p41fwp9khe3qv",
    "tags": [
      "editor/locked"
    ]
  },
  {
    "entity": "@dreamlab/Marker",
    "args": {
      "width": 64.13,
      "height": 60.12
    },
    "transform": {
      "position": {
        "x": -11162.005691383261,
        "y": 72.3877049169248
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "jl8bkg0ulq5c8uansxeefjua",
    "tags": [
      "spawnpoint"
    ]
  },
  {
    "entity": "@dreamlab/Marker",
    "args": {
      "width": 61.86,
      "height": 57.07
    },
    "transform": {
      "position": {
        "x": -10922.586477090003,
        "y": 65.6537804633414
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "oo23g00ygy4t5rjdnr8jjaor",
    "tags": [
      "spawnpoint"
    ]
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1257.6768046903626,
      "height": 827.9956027849031,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/shed-1703001927711.png"
      }
    },
    "transform": {
      "position": {
        "x": 3781.154460222077,
        "y": 171.5174440071509
      },
      "rotation": 0,
      "zIndex": -6
    },
    "uid": "ngdju3e3ti4mr920f127v5s8",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 2467.2567462780207,
      "height": 1353.316233052401,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/saloon-1703001917222.png"
      }
    },
    "transform": {
      "position": {
        "x": 5724.95131070687,
        "y": -79.47112649174755
      },
      "rotation": 0,
      "zIndex": -3
    },
    "uid": "h216rerpcxjas8udy35z0otr",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 2373.3922019152997,
      "height": 1587.8343715646763,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/house3-1703001875315.png"
      }
    },
    "transform": {
      "position": {
        "x": 8705.54671679699,
        "y": -206.92065882037392
      },
      "rotation": 0,
      "zIndex": -6
    },
    "uid": "myl4nnpbn750hy90u15y35za",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 496.8198046194793,
      "height": 443.13991711252,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/boxes-1703001772268.png"
      }
    },
    "transform": {
      "position": {
        "x": 6653.649634525363,
        "y": 249.2921799954675
      },
      "rotation": 0,
      "zIndex": -6
    },
    "uid": "llrzb3m3x4anift4bordescf",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 522.9754488823746,
      "height": 438.6954928545257,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/boxes-1703001772268.png"
      }
    },
    "transform": {
      "position": {
        "x": 6960.540540124339,
        "y": 337.30271418040223
      },
      "rotation": 1.28335384594906,
      "zIndex": -5
    },
    "uid": "pojzf369qn8lcenlcjv2uodc",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 148.11205846528537,
      "height": 209.01339829476265,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/barrel-1703001768203.png"
      }
    },
    "transform": {
      "position": {
        "x": 6829.548699499651,
        "y": 448.8738535383124
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "gcyhibd2cibggcg54nfv3mry",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 149.02536027957285,
      "height": 199.0479917383666,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/barrel-1703001768203.png"
      }
    },
    "transform": {
      "position": {
        "x": 6963.547771816422,
        "y": 478.5898508258732
      },
      "rotation": 11.028347162303165,
      "zIndex": 1
    },
    "uid": "whoof3timsjmzwyvfkzyc3zg",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 152.00974421437422,
      "height": 212.91108404384897,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/barrel-1703001768203.png"
      }
    },
    "transform": {
      "position": {
        "x": 6712.516860113205,
        "y": 413.7922051269855
      },
      "rotation": 0,
      "zIndex": -5
    },
    "uid": "t6wnpy8qkod3kd18mgm1t7xh",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 152.0097442143724,
      "height": 197.32034104750312,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/barrel-1703001768203.png"
      }
    },
    "transform": {
      "position": {
        "x": 6707.73742630245,
        "y": 239.42460113807977
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "kaabn43tr62a0ddnngq55ond",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 116.93057247259276,
      "height": 170.03654080389754,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/barrel-1703001768203.png"
      }
    },
    "transform": {
      "position": {
        "x": 6711.6464618363925,
        "y": 8.432887221991052
      },
      "rotation": 1.0967135231532827,
      "zIndex": -5
    },
    "uid": "zrx40on7nse31h307ktq3yft",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 433.76860040775364,
      "height": 625.4597663121846,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/well-1703001959001.png"
      }
    },
    "transform": {
      "position": {
        "x": -847.2628292198876,
        "y": 282.97792554273997
      },
      "rotation": 0,
      "zIndex": 1
    },
    "uid": "msagioi5jps0lm0nwg00px44",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 316.5126834339967,
      "height": 227.68000381239284,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/wellFront-1703001962312.png"
      }
    },
    "transform": {
      "position": {
        "x": -824.9551126522852,
        "y": 485.3930968114799
      },
      "rotation": 0,
      "zIndex": 11
    },
    "uid": "h3pdiqjsgds2ok0zcua5pwdb",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 87.37380700026642,
      "height": 44.730381373072305,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave11-1703001861494.png"
      }
    },
    "transform": {
      "position": {
        "x": -332.5910581313508,
        "y": 8219.614296722159
      },
      "rotation": 10.613308631731112,
      "zIndex": -6
    },
    "uid": "cd0clqrwkrjwwi75o1xg0274",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 67.97362948268619,
      "height": 76.67489842833675,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave10-1703001859643.png"
      }
    },
    "transform": {
      "position": {
        "x": 1351.9504787696815,
        "y": 8292.377892530132
      },
      "rotation": 3.9338425958331533,
      "zIndex": -6
    },
    "uid": "ip1snc6ns7tk06ocqsetbytr",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 100,
      "height": 100,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave8-1703001855620.png"
      }
    },
    "transform": {
      "position": {
        "x": 2736.732729091514,
        "y": 8275.419976218203
      },
      "rotation": -0.49182705137175214,
      "zIndex": -6
    },
    "uid": "ipssvfg8j09weex4p2sk7iao",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 266.1391666715281,
      "height": 232.3995127788221,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave6-1703001847085.png"
      }
    },
    "transform": {
      "position": {
        "x": 2435.386345438057,
        "y": 8244.829178145274
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "f1nsoa4dwiobt521xsweh8kn",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 140.5965893033267,
      "height": 163.09429346987417,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave9-1703001857904.png"
      }
    },
    "transform": {
      "position": {
        "x": -2508.6641817180393,
        "y": 8255.020172648901
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "wwpixcxl0oartfwl9tuzmzjo",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 281.7516888435348,
      "height": 268.02679660358444,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave-1703001836190.png"
      }
    },
    "transform": {
      "position": {
        "x": -962.7784568070155,
        "y": 8244.623069170018
      },
      "rotation": 0,
      "zIndex": 12
    },
    "uid": "l8xqseb9bugx3iid9xhuxqw8",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 97.10115177732769,
      "height": 98.8022736510211,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave3-1703001839817.png"
      }
    },
    "transform": {
      "position": {
        "x": 699.2477884903183,
        "y": 8276.735124156181
      },
      "rotation": 0,
      "zIndex": -6
    },
    "uid": "nz0c8gzrwpsnjfi6wl5s20zq",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 180.2291553477935,
      "height": 221.25456761462192,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave3-1703001839817.png"
      }
    },
    "transform": {
      "position": {
        "x": 912.918804092345,
        "y": 8232.11094834374
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "pgq32a1pobbrd2dzzy1nb8xm",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 237.94487466488576,
      "height": 236.13534390891073,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave8-1703001855620.png"
      }
    },
    "transform": {
      "position": {
        "x": 47.14553837759581,
        "y": 8228.219021095045
      },
      "rotation": -5.09809412162101,
      "zIndex": -2
    },
    "uid": "mijap11ov7331nhikoblspcp",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 183.71520170259487,
      "height": 214.8251208819256,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave10-1703001859643.png"
      }
    },
    "transform": {
      "position": {
        "x": 1925.1519609455818,
        "y": 8228.89622497996
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "qotbf7lno3sx89344kwtnjpn",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 288.31828459951794,
      "height": 282.8076876194209,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave6-1703001847085.png"
      }
    },
    "transform": {
      "position": {
        "x": -2252.6019560235736,
        "y": 8217.156709388015
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "vdw1hx7jugoimes5blk75tdl",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 86.28197799306508,
      "height": 110.72292996755823,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave3-1703001839817.png"
      }
    },
    "transform": {
      "position": {
        "x": -2976.874853833026,
        "y": 8274.822209174205
      },
      "rotation": 1.213223246785825,
      "zIndex": -6
    },
    "uid": "l2k3xt2lvkwhq7faa488ozl9",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 254.40032395519393,
      "height": 264.0057946740217,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave4-1703001841648.png"
      }
    },
    "transform": {
      "position": {
        "x": 1043.3674334591992,
        "y": 8239.844661754054
      },
      "rotation": 0,
      "zIndex": 11
    },
    "uid": "h7k83o20k4oe41isyj4a28pa",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 243.2318159434344,
      "height": 224.5118402984299,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave2-1703001838061.png"
      }
    },
    "transform": {
      "position": {
        "x": -2064.896300325524,
        "y": 8224.041520816238
      },
      "rotation": 9.861153109249459,
      "zIndex": -2
    },
    "uid": "frefsf906yhf0i2dsgzbq2df",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 261.3703225479476,
      "height": 318.3664069146889,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave12-1703001863530.png"
      }
    },
    "transform": {
      "position": {
        "x": 1619.8765439480185,
        "y": 8213.849360005463
      },
      "rotation": 0,
      "zIndex": 12
    },
    "uid": "rflfs78o20wqvhhgghkf1ekf",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 344.9084816547088,
      "height": 224.75033599510152,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave11-1703001861494.png"
      }
    },
    "transform": {
      "position": {
        "x": -3485.8686520505626,
        "y": 8230.814952084795
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "mase92yh2l719fhmqrdsr6h7",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 232.2778939985419,
      "height": 281.12058464242,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave10-1703001859643.png"
      }
    },
    "transform": {
      "position": {
        "x": -4190,
        "y": 8230
      },
      "rotation": 0,
      "zIndex": 12
    },
    "uid": "h25kxrgiaeo565xzjavosz8s",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 187.45171560013296,
      "height": 211.69305724792503,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave5-1703001843591.png"
      }
    },
    "transform": {
      "position": {
        "x": -535.6084988512382,
        "y": 8222.578407913728
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "czvipk1i8bbunlh86x9iytgp",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 41272.820261272005,
      "height": 436.7299610656373,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/groundX-1703001868400.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -1581.6833975894006,
        "y": 8528.509693104008
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "qbk45uaqlwagsgsy23zto0kz",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 711.9022445044183,
      "height": 635.5151680663557,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/stonePlatform1-1703004877657.png"
      }
    },
    "transform": {
      "position": {
        "x": -1277.2244736484042,
        "y": 6217.912440675544
      },
      "rotation": -0.726190044634089,
      "zIndex": -3
    },
    "uid": "zhxl9z0rowv35d3yykbmupuq",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 40373.92860159948,
      "height": 680.0623695512452,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/ground3X-1703262997778.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": 833.8521612852892,
        "y": 906.3568028804884
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "iosovfvg4oio488rpe9hydu0",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 40331.759838026206,
      "height": 907.267020389057,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/blackXY-1703001770204.png"
      }
    },
    "transform": {
      "position": {
        "x": 866.712268665593,
        "y": 1694.0737386753028
      },
      "rotation": 0,
      "zIndex": 11
    },
    "uid": "ts7jaer1lwt9nxb1v5cnn181",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 166.1866208470724,
      "height": 346.86279683377626,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/shopkeeper2-1703001938327.png"
      }
    },
    "transform": {
      "position": {
        "x": -4035.6339033555114,
        "y": 368.8247195591159
      },
      "rotation": 0,
      "zIndex": -7
    },
    "uid": "hkmd4qs7bzeey65zhdynhxwh",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 947.0812364545004,
      "height": 512.2325835321312,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/martkeStall2-1703001892985.png"
      }
    },
    "transform": {
      "position": {
        "x": -3847.0661887011374,
        "y": 323.06348583754107
      },
      "rotation": 0,
      "zIndex": 1
    },
    "uid": "jh8psbu111umjqvol0xy7rgd",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -845.5496412800994,
        "y": 2380.8774109413584
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "jzbcrtqlezniqgilmsu9p7g4",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -845.7990280623333,
        "y": 2879.131229216744
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "p4iicl1iy6znrhnlw8l7zzr5",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -845.5575568473816,
        "y": 3377.61547776258
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "c3n1xuqxptpjxy1qa232ner4",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -845.5575568473816,
        "y": 3876.036726047462
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "i7gq3jg7wyohgo2jixoi5uya",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -846.1837078930521,
        "y": 4374.301947710202
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "rs42pqq0nl76vwu7vhvsblif",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -845.9797204357719,
        "y": 4872.788564881131
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "psggcsciapxc0w5j8rnhyk18",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -844.3948825582302,
        "y": 5371.032192867339
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "nn5pevm8yu1h8906tkbmsvky",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 421.58047493403694,
      "height": 498.49959133194034,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bricksY-1703284359242.png"
      }
    },
    "transform": {
      "position": {
        "x": -843.5874601015596,
        "y": 5869.410479774948
      },
      "rotation": 0,
      "zIndex": 11
    },
    "uid": "fggkg56ru7tvvhv94mjo9z13",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 381.04290397566774,
      "height": 307.0081888903378,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/stonePlatform1-1703004877657.png"
      }
    },
    "transform": {
      "position": {
        "x": -835.276843533451,
        "y": 6112.274738133623
      },
      "rotation": 26.5851020374852,
      "zIndex": 10
    },
    "uid": "bdbtro2yhfmeucaoqvzn46ne",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 2778.924988889837,
      "height": 167.4010554088909,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/xyz-1703001967292.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -5863.667546174143,
        "y": 8092.981530343009
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "y72truf941i2cto7og3m0h9c",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1007.3106515257024,
      "height": 323.7619239454589,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform47-1703289214986.png"
      }
    },
    "transform": {
      "position": {
        "x": -7871.4631392650845,
        "y": 7948.627044293755
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "ajj65ei17nptuxcmdt7c3j4c",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 573.0560807781403,
      "height": 674.2992034265926,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform44-1703375415181.png"
      }
    },
    "transform": {
      "position": {
        "x": -6787.649109451249,
        "y": 7494.312448694727
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "hspeadfvyu4p7n3rs7el13fd",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 573.0560807781403,
      "height": 674.2992034265926,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform45-1703375406684.png"
      }
    },
    "transform": {
      "position": {
        "x": -7473.683276737472,
        "y": 7165.498989722008
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "ku296tz0n0kz4l7gojfhxvu9",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 2889.4682206144635,
      "height": 170.64309268520083,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/xyz-1703001967292.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -5182.690395857981,
        "y": 6961.853648688164
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "tob6ecgcccdz1ggayx0g2ti1",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 993.0076625751848,
      "height": 539.556454082347,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform36-1703375910696.png"
      }
    },
    "transform": {
      "position": {
        "x": -4274.842782989425,
        "y": 5518.274075995303
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "y93q5yfmd1o61l57hmti17pg",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 2889.4682206144635,
      "height": 170.64309268520083,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/xyz-1703001967292.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -2490.3156653122464,
        "y": 5510.351824371257
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "otza7y33t1a5bq9h6p4mg0f2",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 633.7809487690088,
      "height": 233.14198844264504,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform47-1703289214986.png"
      }
    },
    "transform": {
      "position": {
        "x": -2791.618391446641,
        "y": 6682.462194963722
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "avw046m1q6l8rfqd05mi3adq",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 4352.838829466731,
      "height": 164.91160949864116,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/xyz-1703001967292.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -10601.830778467354,
        "y": 7280.722298978726
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "k0bpdq7b3mrmlia3culyrb9a",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 725.0989835440432,
      "height": 446.052769287493,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform37-1703376090016.png"
      }
    },
    "transform": {
      "position": {
        "x": -16074.26739222129,
        "y": 8187.787601826877
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "hehv7gk2cgd1hchrw9jsykjy",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1266.163310508644,
      "height": 770.4719037025634,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform3-1703001903285.png"
      }
    },
    "transform": {
      "position": {
        "x": -14210.809656962912,
        "y": 7875.723023417897
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "nct7ryrinc8tbmqibt5t5j2e",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 455.02018909986873,
      "height": 497.31850783047594,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform46-1703375411980.png"
      }
    },
    "transform": {
      "position": {
        "x": -14067.319360634956,
        "y": 7195.602352534346
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "uqj53tcxrgmd0czpvvrcbwpz",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1738.00319995081,
      "height": 228.23743635395203,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/xyz-1703001967292.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -15634.154140328066,
        "y": 6911.5964931610015
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "o6onkglejok33isa719gbe5a",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1119.8115664066572,
      "height": 487.81248053922536,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform34-1703376107235.png"
      }
    },
    "transform": {
      "position": {
        "x": -12613.374380344208,
        "y": 8147.453737133925
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "tl9a3gwlhc4wtlui496mzpp7",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 633.7809487690088,
      "height": 233.14198844264504,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform47-1703289214986.png"
      }
    },
    "transform": {
      "position": {
        "x": 3162.2270120070725,
        "y": 8131.515834594526
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "rp1de75gq7wpa26j7iavugz8",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 2209.3529363890675,
      "height": 227.48687016944405,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/xyz-1703001967292.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": 5231.255312717676,
        "y": 7817.065004717791
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "wbc20rsjgmpc2aa4wafv53cd",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 693.8859599111711,
      "height": 449.25638301044455,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform34-1703376107235.png"
      }
    },
    "transform": {
      "position": {
        "x": 6969.7385440655435,
        "y": 7496.0216282905685
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "dfkiz3isrbplbtle05z65y57",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1105.2183438543461,
      "height": 230.9985515973267,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform6X-1703291285081.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": 5606.400844375017,
        "y": 7710.050158772578
      },
      "rotation": -0.10705627505046926,
      "zIndex": -6
    },
    "uid": "x44tmcexqlxdworhmf8nxz9b",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1137.1485227714884,
      "height": 659.256441798203,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform36-1703375910696.png"
      }
    },
    "transform": {
      "position": {
        "x": 5311.249296213313,
        "y": 6688.008911406981
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "vx0nvs3hsjw6gluoc8wuc56r",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 693.8859599111711,
      "height": 449.25638301044455,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform44-1703375415181.png"
      }
    },
    "transform": {
      "position": {
        "x": 7380.43887214619,
        "y": 7127.5872436722175
      },
      "rotation": 0,
      "zIndex": -5
    },
    "uid": "bhysssc9y0lzmjc5g7uqmwpn",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 398.602610562446,
      "height": 373.7482442756709,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform45-1703375406684.png"
      }
    },
    "transform": {
      "position": {
        "x": 6616.1455216740915,
        "y": 6786.571416530115
      },
      "rotation": 0,
      "zIndex": -5
    },
    "uid": "keg48d1g71g17zc9apuig34v",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 694.6919418854468,
      "height": 565.0866759447072,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform46-1703375411980.png"
      }
    },
    "transform": {
      "position": {
        "x": 5730.452016392335,
        "y": 6081.533241670999
      },
      "rotation": 0,
      "zIndex": -5
    },
    "uid": "a4ndhbeyycj3r1znc4s8q6uw",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 878.9594241708264,
      "height": 425.58152782792604,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform35-1703375427203.png"
      }
    },
    "transform": {
      "position": {
        "x": 7066.697443053792,
        "y": 5914.379973326251
      },
      "rotation": 0,
      "zIndex": -5
    },
    "uid": "uelsg681pk00ge7l5cm8mww6",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 878.9594241708264,
      "height": 425.5815278279261,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform34-1703376107235.png"
      }
    },
    "transform": {
      "position": {
        "x": 8558.224274690681,
        "y": 5552.660957361417
      },
      "rotation": -17.565413350422148,
      "zIndex": -5
    },
    "uid": "zgv2gt11g15yvby2lyj2nfu4",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 3082.0382837323045,
      "height": 229.96498691430224,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/xyz-1703001967292.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": 3316.7123893011167,
        "y": 6488.727331568292
      },
      "rotation": 0,
      "zIndex": -5
    },
    "uid": "wdvmt10t9oq2uwftil2cukod",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 34298.07319131977,
      "height": 781.6490765174162,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/townBG2X-1703001949245.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -2206.194909316813,
        "y": 171.38712568348188
      },
      "rotation": 0,
      "zIndex": -11
    },
    "uid": "rzderw50hhlz49s0cs3o7z9i",
    "tags": [
      "editor/locked"
    ]
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 6480.862900786258,
      "height": 4160.813370802238,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/sandstormXY-1703001923602.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -16317.490768221965,
        "y": -1300.7049180193007
      },
      "rotation": 0,
      "zIndex": -1
    },
    "uid": "muuyilyvv4skqlhj3omajdov",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1287.405672823219,
      "height": 4354.951846965699,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/sandstormGradientRight-1703438789434.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -12435.988226413152,
        "y": -1202.4136661533503
      },
      "rotation": 0,
      "zIndex": -1
    },
    "uid": "dp5k2hi7yevkot2bqmq945ea",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 798.3838886161202,
      "height": 800.4368708783054,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/marketStall1-1703001885700.png"
      }
    },
    "transform": {
      "position": {
        "x": -2603.1046459770914,
        "y": 222.09299028940552
      },
      "rotation": 0,
      "zIndex": -11
    },
    "uid": "ojsycwdtufktcsx1pfcfmqwx",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1291.884214853384,
      "height": 8855.72755728318,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/sandstormGradientLeft-1703001919439.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": 10923.020218390337,
        "y": -771.6657438119956
      },
      "rotation": 0,
      "zIndex": -3
    },
    "uid": "grv7enww1yetg3frz3oeq9j0",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 3520.511483367567,
      "height": 8851.32242740075,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/sandstormXY-1703001923602.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": 13326.715383304123,
        "y": -774.6010248559858
      },
      "rotation": 0,
      "zIndex": -3
    },
    "uid": "nle4w6feddprus5a0x4616ex",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 37791.11657449307,
      "height": 529.7841829387162,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/desert2-1703437385249.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -3118.5639543089837,
        "y": 8064.106344724404
      },
      "rotation": 0,
      "zIndex": -10
    },
    "uid": "wpgw81grjrvo8xrq0difd7mn",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 66.96066207528202,
      "height": 35.035934550213824,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave11-1703001861494.png"
      }
    },
    "transform": {
      "position": {
        "x": -2716.7826040587947,
        "y": 8226.132331626031
      },
      "rotation": 10.06068979532229,
      "zIndex": -6
    },
    "uid": "omvb5bb0aqbbydnqabqxy8by",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 565.1277469590277,
      "height": 136.5163242555236,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform6X-1703291285081.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -2790.9186216604066,
        "y": 6529.0693750481105
      },
      "rotation": -0.10705627505046926,
      "zIndex": -6
    },
    "uid": "ru8toq2q49f88q7awkwc7w5j",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 989.5012138341572,
      "height": 516.2150395778372,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform2-1703001900992.png"
      }
    },
    "transform": {
      "position": {
        "x": -6114.587442546614,
        "y": 5919.750285343454
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "n6pbctsq55f9ambj6we0vkva",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 100,
      "height": 100
    },
    "transform": {
      "position": {
        "x": -7471.060959709848,
        "y": 8165.895758185566
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "owoa0xinqwudy5uwxoq3y6q8",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 41214.3358073866,
      "height": 2145.44827349958,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/stoneXY-1703444958077.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -1526.3293386351324,
        "y": 9591.162509350253
      },
      "rotation": 0,
      "zIndex": -4
    },
    "uid": "rvebkrmhjf96o5432nzbfbwy",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 87.64027477856553,
      "height": 87.64027477856553,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/bird-1703445269470.png"
      }
    },
    "transform": {
      "position": {
        "x": 993.6364257972498,
        "y": -2169.0039937463935
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "p667rdat1kdd78j6xtobxsec",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 174.02,
      "height": 349,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/girl1-1703445910095.png"
      }
    },
    "transform": {
      "position": {
        "x": -1528.7481674242872,
        "y": 391.52443294851264
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "tzyfbga57f2pjfkh75l9t5zq",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 35686.51304828707,
      "height": 6262.455193203618,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/sky3XY-1703443714062.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -1451.7752378425175,
        "y": 5275.29457285924
      },
      "rotation": 0,
      "zIndex": -12
    },
    "uid": "lwpukbepq4az4vo98ls7t7ii",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 347.5145118733508,
      "height": 523.2401055408973,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/cactus1-1703001776754.png"
      }
    },
    "transform": {
      "position": {
        "x": -10440.592840600986,
        "y": 8107.368736973895
      },
      "rotation": 0,
      "zIndex": 11
    },
    "uid": "gvgc2bcaqkcrwkeg89gts7bs",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 463.60949868073885,
      "height": 444.0844327176774,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/cactus2-1703001779132.png"
      }
    },
    "transform": {
      "position": {
        "x": -1609.3389826236148,
        "y": 8152.030346471955
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "t1pwqxfj69y5z8qucxjb28od",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 468.94195250659686,
      "height": 552.8469656992083,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/cactus3-1703001780890.png"
      }
    },
    "transform": {
      "position": {
        "x": 7227.579494759503,
        "y": 8092.427444096628
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "hr3cinmqhfq4thzwcteyzzc7",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 2628.91,
      "height": 1216.24,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/workshop-1703001965089.png"
      }
    },
    "transform": {
      "position": {
        "x": -7511.330764067422,
        "y": -18.33992190107108
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "igr1el06yytw922jhvegjwk2",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 618.3,
      "height": 233.52,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/counter-1703001788599.png"
      }
    },
    "transform": {
      "position": {
        "x": -8062.797313532223,
        "y": 443.8528986853157
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "m4s09111am0hx9dm7xhh3q1o",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 251.2,
      "height": 410.62,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/shopkeep-1703001936455.png"
      }
    },
    "transform": {
      "position": {
        "x": -8754.963867193019,
        "y": 349.886392477303
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "mx7fqit3vu1tx3i01idlgzdu",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1630.88,
      "height": 651.95,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/-1710274317994-removebg-preview-1710274506549.png"
      }
    },
    "transform": {
      "position": {
        "x": -11939.774739589227,
        "y": 300.74876608849684
      },
      "rotation": 0,
      "zIndex": -2
    },
    "uid": "dmwn7dtvog7s8ma8o4qju0xj",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 184.74,
      "height": 438.68,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/-1710274600477.png"
      }
    },
    "transform": {
      "position": {
        "x": -10042.97113169284,
        "y": 380.35227084323253
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "hsekx8zqzoda12bx0gd8k0bv",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1053.63,
      "height": 795.19,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/shed-1703001927711.png"
      }
    },
    "transform": {
      "position": {
        "x": -5468.055276861901,
        "y": 190.86951462547586
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "w7i9lys8bdiadm70i5j8bkth",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 178.39,
      "height": 350.61,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/boy1-1703445894865.png"
      }
    },
    "transform": {
      "position": {
        "x": -5115.659308976299,
        "y": 387.6342774654497
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "ndf0ncw2gt50qsnirk9ikk81",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 423.29,
      "height": 438.67,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/boxes-1703001772268.png"
      }
    },
    "transform": {
      "position": {
        "x": -4927.775381784763,
        "y": 379.72273843668677
      },
      "rotation": 0,
      "zIndex": -1
    },
    "uid": "wzxpq7rhbp8gmgjpz2esn4y2",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 333.39,
      "height": 248.73,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/counter-1703001788599.png"
      }
    },
    "transform": {
      "position": {
        "x": -7338.10429951044,
        "y": 453.0826140793753
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "s8t3ju8t5dtkyegwa37s2y8k",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 34323.333113456465,
      "height": 338.89907651715043,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/townBG1X-1703001946840.png",
        "tile": true
      }
    },
    "transform": {
      "position": {
        "x": -1082.9954054565028,
        "y": 462.3012036213162
      },
      "rotation": 0,
      "zIndex": -10
    },
    "uid": "smuszccpapv7hud59dziit3q",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 168.47,
      "height": 246.69,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave9-1703001857904.png"
      }
    },
    "transform": {
      "position": {
        "x": 1368.5474507103088,
        "y": 453.4263910696807
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "km9nif7210p2fmk265vswpcz",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 143.06,
      "height": 118.28,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave6-1703001847085.png"
      }
    },
    "transform": {
      "position": {
        "x": 1746.9531866055036,
        "y": 386.0922446415533
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "zpu5prw1ej0h6x3fhieh2bpr",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 91.78,
      "height": 124.6,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave12-1703001863530.png"
      }
    },
    "transform": {
      "position": {
        "x": 727.2673214755846,
        "y": 386.1111592843657
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "p7msyiiapu1ta79rh4b8p7d1",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 207.36,
      "height": 196.14,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave4-1703001841648.png"
      }
    },
    "transform": {
      "position": {
        "x": 352.31963761229855,
        "y": 509.6798252125556
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "g27wlfryh8bn0l07ea28vhbd",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 144.85,
      "height": 138.12,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave8-1703001855620.png"
      }
    },
    "transform": {
      "position": {
        "x": 2086.509955140487,
        "y": 477.53886421268
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "xbron2hnvqhuhmpvyyvib8er",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 79.17,
      "height": 70.65,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave-1703001836190.png"
      }
    },
    "transform": {
      "position": {
        "x": 1069.0370282823046,
        "y": 381.0925470701778
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "tlo0vyfq14pc7qqxdqbpycs6",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 73.49,
      "height": 60.09,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/grave5-1703001843591.png"
      }
    },
    "transform": {
      "position": {
        "x": 272.8431306169989,
        "y": 325.6353226418014
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "riovocneubm7budt2mq1d4tw",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1922.83,
      "height": 977.65,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform3-1703001903285.png"
      }
    },
    "transform": {
      "position": {
        "x": 9284.598578971203,
        "y": -1616.185290404237
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "o2hass9qbe4nby6icv2swe8r",
    "tags": []
  },
  {
    "entity": "@dreamlab/Nonsolid",
    "args": {
      "width": 1092.87,
      "height": 928.32,
      "spriteSource": {
        "url": "https://s3-assets.dreamlab.gg/uploaded-from-editor/platform45-1703375406684.png"
      }
    },
    "transform": {
      "position": {
        "x": 7366.394615841022,
        "y": -825.4182657395365
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "wwbdmbp3bkew3odofgtsac0i",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 2295.294420413703,
      "height": 50.246984077163006
    },
    "transform": {
      "position": {
        "x": 5715.533437927633,
        "y": 474.34556386499605
      },
      "rotation": 0,
      "zIndex": 111
    },
    "uid": "wf2mci66nkb3phiksafpgd8g",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 2347.3879968897018,
      "height": 38.57308302687943
    },
    "transform": {
      "position": {
        "x": 5712.399183816415,
        "y": -92.85427779479562
      },
      "rotation": 0,
      "zIndex": 112
    },
    "uid": "rpkpv7lte1yg7oiah61ebjcf",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 959.179186515209,
      "height": 49.39538292414761
    },
    "transform": {
      "position": {
        "x": 3773.70743581841,
        "y": 54.54018719135178
      },
      "rotation": 0,
      "zIndex": 108
    },
    "uid": "jdkgdemfo2pg58z3ghrsw4uk",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 138.3657017222431,
      "height": 25.943569072920468
    },
    "transform": {
      "position": {
        "x": 4325.363190722178,
        "y": 253.5210580771704
      },
      "rotation": 0,
      "zIndex": 107
    },
    "uid": "v168citrbja2uqtpvyqg1hbg",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 39.4046523810639,
      "height": 62.943109879558534
    },
    "transform": {
      "position": {
        "x": 3411.975063774883,
        "y": -199.41044337592848
      },
      "rotation": 0,
      "zIndex": 110
    },
    "uid": "hstf2l4m0fgp83n642llsul8",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 40.738513320392485,
      "height": 68.25353266810117
    },
    "transform": {
      "position": {
        "x": 4145.286370631852,
        "y": -197.75606813871343
      },
      "rotation": 0,
      "zIndex": 109
    },
    "uid": "mc5zi49veaf1vds8sl3knro2",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 122.2586555810076,
      "height": 27.04287284719771
    },
    "transform": {
      "position": {
        "x": 3267.7607631761075,
        "y": 413.42280075242616
      },
      "rotation": 0,
      "zIndex": 106
    },
    "uid": "vmpaivytp6ku9zoi3mjobajj",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 97.679998528939,
      "height": 37.00846212770273
    },
    "transform": {
      "position": {
        "x": 6981.603771527682,
        "y": 414.4190230355021
      },
      "rotation": 0,
      "zIndex": 113
    },
    "uid": "gxtkbfzru1lyws3h6kjh9vix",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 175.39585870888914,
      "height": 57.003654080389765
    },
    "transform": {
      "position": {
        "x": 7126.856346584808,
        "y": 442.1592671970712
      },
      "rotation": 0,
      "zIndex": 114
    },
    "uid": "icfzuhl7x7cfxq0xrzcy90vb",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 286.6639737353171,
      "height": 54.56542799813826
    },
    "transform": {
      "position": {
        "x": 6992.968714037274,
        "y": 208.2571422563114
      },
      "rotation": 0,
      "zIndex": 115
    },
    "uid": "pnti0sqj9pcyvyutxwyzmvqq",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 2221.712401055409,
      "height": 36.48812664907655
    },
    "transform": {
      "position": {
        "x": 5717.186292963131,
        "y": -239.1145651767899
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "sbv5pflynx1mpmit5rnxa1gy",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 1075.4063324538256,
      "height": 55.77044854881274
    },
    "transform": {
      "position": {
        "x": 8069.202435890322,
        "y": -319.99391482290196
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "p8wsi8bgm7q4huynzda10n9q",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 2752.3687335092336,
      "height": 116.96306068601552
    },
    "transform": {
      "position": {
        "x": -5861.9958260823605,
        "y": 8084.457455069323
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ol3pultk3eouz4zhmmemobet",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 971.9762532981532,
      "height": 118.80386545097554
    },
    "transform": {
      "position": {
        "x": -7869.814820803459,
        "y": 7857.872029793969
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "wfr0qjdus28avlyeng43y3je",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 402.39577836411627,
      "height": 58.86015831134591
    },
    "transform": {
      "position": {
        "x": -6772.440642035351,
        "y": 7488.039503906187
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "x2fmnoh1pybnb28m99kork93",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 516.7097625329825,
      "height": 62.09234828496028
    },
    "transform": {
      "position": {
        "x": -7461.787152841943,
        "y": 7159.781824024356
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "gj0pyeernrp8ut9rki4dj2vq",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 2866.705458644423,
      "height": 112.09221719178096
    },
    "transform": {
      "position": {
        "x": -5189.147948316137,
        "y": 6936.247819944108
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "rdvn6himc36oknrkktbne57h",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 610.3667546174147,
      "height": 97.96569920844377
    },
    "transform": {
      "position": {
        "x": -2790.843232032056,
        "y": 6622.766258479309
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "t08x0folcnwu3x1x8dkqdqji",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 3531.9611178631576,
      "height": 121.90590850773242
    },
    "transform": {
      "position": {
        "x": -2795.7877918818785,
        "y": 5484.355285458072
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "k2yjwik4kcgalz40ij22vh7y",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 4338.067770638298,
      "height": 122.61382903492904
    },
    "transform": {
      "position": {
        "x": -10602.05358752106,
        "y": 7266.756853238727
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "hatwg6fawsmpwjii8eldz15p",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 226.19788918205813,
      "height": 99.55376408614484
    },
    "transform": {
      "position": {
        "x": -4617.875210971768,
        "y": 5322.21341571636
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "djoftnoqylbsbdg6drp4jpqy",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 685.8339404183534,
      "height": 88.87321982849335
    },
    "transform": {
      "position": {
        "x": -16066.805003777348,
        "y": 8095.094924722627
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "y7qoigfwsemp0o1r7g5c6r0b",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 1166.1055408970933,
      "height": 131.73878627968315
    },
    "transform": {
      "position": {
        "x": -14237.262911249987,
        "y": 7879.894462565237
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "wcnyp10d6il8pukfepwchewb",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 250.9360667118981,
      "height": 112.76899819206938
    },
    "transform": {
      "position": {
        "x": -13720.33384698061,
        "y": 7577.661547413249
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "lg3spsuuk3yslmouhc8lsqpb",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 373.63526431756145,
      "height": 169.16081877174474
    },
    "transform": {
      "position": {
        "x": -14057.213269810143,
        "y": 7245.697028198276
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "n6vw591g6r2gdjdfhp2he8n5",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 1708.1209168963396,
      "height": 155.32778557928123
    },
    "transform": {
      "position": {
        "x": -15628.58109988764,
        "y": 6879.649016547788
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "mnqkthy23gtt7drstlbefwe3",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 1058.5197889182054,
      "height": 103.65849571407216
    },
    "transform": {
      "position": {
        "x": -12614.39076072927,
        "y": 8041.691863783
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "yzk7qyr3epe9ikwepjd7w3yh",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 618.1364641915156,
      "height": 108.87877376357484
    },
    "transform": {
      "position": {
        "x": 3160.5278343722666,
        "y": 8078.29187612416
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "cv5uzj7bzli15omyfpotwwne",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 2209.0216956996164,
      "height": 121.89872554677095
    },
    "transform": {
      "position": {
        "x": 5227.497299002136,
        "y": 7769.331063882254
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "le0hmtb3ksep73lrwsqnl0zu",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 671.6070731405543,
      "height": 86.0369393139863
    },
    "transform": {
      "position": {
        "x": 6963.135448985074,
        "y": 7395.4853518982245
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ecvbgh3ct02rsyweab6xtog0",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 503.3198761415497,
      "height": 83.01288395087795
    },
    "transform": {
      "position": {
        "x": 7413.171702846333,
        "y": 7151.867652226371
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ws9jsbr08lf78iisiygab0vj",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 363.18980698346604,
      "height": 60.59674582233947
    },
    "transform": {
      "position": {
        "x": 6627.592779905084,
        "y": 6795.250593539603
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "tzhyk55w7mc0e10g0kearcut",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 885.4327176781007,
      "height": 64.32453825857465
    },
    "transform": {
      "position": {
        "x": 5407.852141592022,
        "y": 6617.8076913873865
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "nii33fx2lbz35ghel64zg7f1",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 3274.4130718175666,
      "height": 99.4273095392382
    },
    "transform": {
      "position": {
        "x": 3415.7691764835895,
        "y": 6431.568729622579
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "a8zg9mzymkybs9yeogxvprq5",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 618.8986149976708,
      "height": 59.40538677987024
    },
    "transform": {
      "position": {
        "x": 5743.358233838029,
        "y": 6076.388117230669
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "en1kdy4egtzwb0uxmpan4f8y",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 810.7131597415801,
      "height": 49.70005486750779
    },
    "transform": {
      "position": {
        "x": 7075.529818321669,
        "y": 5787.526947023245
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ceud8uehm94q2bul1933ipsy",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 969.8654353562015,
      "height": 102.15204151944727
    },
    "transform": {
      "position": {
        "x": -6110.283020316719,
        "y": 5880.402140953574
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "k2qfimuc0be6as8ig2rtzzzl",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 988.63,
      "height": 50.52
    },
    "transform": {
      "position": {
        "x": 8070.215858522866,
        "y": -559.5454152057254
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "r4bo31a6teeukskzg39t6mur",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 617.67,
      "height": 37.55
    },
    "transform": {
      "position": {
        "x": 6458.49406243918,
        "y": -625.144486409361
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "uei0j6sjroieaosaismuahlt",
    "tags": []
  },
  {
    "entity": "@dreamlab/Platform",
    "args": {
      "width": 647.37,
      "height": 47.52
    },
    "transform": {
      "position": {
        "x": 5009.028142535391,
        "y": -640.8854435497876
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "irphg0nllkckotszis7jt83u",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 21718.933082313393,
      "height": 59.76458497008082
    },
    "transform": {
      "position": {
        "x": 10206.621886183384,
        "y": 599.768455984519
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "jtgnqqzvcf81bfn8dvxve5ld",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 5579.260715955342,
      "height": 58.91698863076908
    },
    "transform": {
      "position": {
        "x": -1015.0314519734304,
        "y": 3367.68711597453
      },
      "rotation": 90,
      "zIndex": 0
    },
    "uid": "eydc375n6kgxu4sdunbusbye",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 5586.833153187934,
      "height": 68.67891323160347
    },
    "transform": {
      "position": {
        "x": -676.6307953560645,
        "y": 3366.7829718205803
      },
      "rotation": 90,
      "zIndex": 0
    },
    "uid": "ruvttcm884ct5luzv67270av",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 37527.19448939468,
      "height": 205.22854289759925
    },
    "transform": {
      "position": {
        "x": 248.62129525237106,
        "y": 8453.436305742476
      },
      "rotation": 0,
      "zIndex": 0
    },
    "uid": "cxmz94liwbz7uda4pjdkk2sj",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 190.49537662323928,
      "height": 1128.1788200806322
    },
    "transform": {
      "position": {
        "x": 11664.113474913042,
        "y": 14.262340883805166
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ks16ze1amc8kmjn0rpr1xpws",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 73.76635939885148,
      "height": 189.36385392541843
    },
    "transform": {
      "position": {
        "x": -683.1342498174956,
        "y": 482.2958970353168
      },
      "rotation": -0.903440835362379,
      "zIndex": 100
    },
    "uid": "svegk6cwg7n3v1p7a4quj17l",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 76.47048107950502,
      "height": 199.25742736042093
    },
    "transform": {
      "position": {
        "x": -1010.7611044152449,
        "y": 482.4999526697384
      },
      "rotation": -0.6897578521300134,
      "zIndex": 100
    },
    "uid": "pkxc7i1gtw14twq7pr4jli17",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 14383.47715324976,
      "height": 67.16474275861106
    },
    "transform": {
      "position": {
        "x": -8228.020388065765,
        "y": 603.1039212456222
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "uh3vkf4myr8k10ey7997chvz",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 44.245584320460694,
      "height": 402.49861615681584
    },
    "transform": {
      "position": {
        "x": -1155.1441154727188,
        "y": 6131.159806622591
      },
      "rotation": 45.706790284749204,
      "zIndex": 100
    },
    "uid": "nvhev75cznyjzu23iqv70wog",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 364.47452310904055,
      "height": 54.41881556992212
    },
    "transform": {
      "position": {
        "x": -1451.0878983341536,
        "y": 6347.682466429699
      },
      "rotation": -26.089269841777785,
      "zIndex": 100
    },
    "uid": "jhxva17214i4shssn7e852uu",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 812.893462308818,
      "height": 98.3080237752738
    },
    "transform": {
      "position": {
        "x": 8539.449794149115,
        "y": 5480.817008785678
      },
      "rotation": -18.152705886650875,
      "zIndex": 100
    },
    "uid": "ahajdlruayhkuj8obhgnjj1q",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 216.74403946286657,
      "height": 889.8599616333241
    },
    "transform": {
      "position": {
        "x": -13789.367555728102,
        "y": 129.22380212322815
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "xu1hqh39urmcgvaaikhegmc5",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 187.17771992326743,
      "height": 12155.638174755768
    },
    "transform": {
      "position": {
        "x": -18572.256089404636,
        "y": 2262.8263103123045
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "ci4a7un2v6jspwti16yw1lwq",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 160.86516853932517,
      "height": 7717.370923540696
    },
    "transform": {
      "position": {
        "x": 11657.262103065324,
        "y": 4492.568871139309
      },
      "rotation": 0,
      "zIndex": 100
    },
    "uid": "xh6ktuib0off5t8c9v49bht0",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 893.92,
      "height": 49.72
    },
    "transform": {
      "position": {
        "x": 8854.762876853063,
        "y": -719.6965098455165
      },
      "rotation": -36.89750863323105,
      "zIndex": 100
    },
    "uid": "vhgtp1ka5nbb8lsvvkg52c7z",
    "tags": []
  },
  {
    "entity": "@dreamlab/Solid",
    "args": {
      "width": 827.04,
      "height": 39.57
    },
    "transform": {
      "position": {
        "x": 9535.264842853072,
        "y": -717.6005328807635
      },
      "rotation": 37.36768282030945,
      "zIndex": 100
    },
    "uid": "xcm33x9eftvzhockx7f2vc75",
    "tags": []
  }
]
