import type { CSSProperties } from 'https://esm.sh/react@18.2.0'

export const inventoryStyles: Record<string, CSSProperties> = {
  inventory: {
    pointerEvents: 'auto',
    display: 'flex',
    flexDirection: 'column',
    border: '3px solid #8c7ae6',
    width: '475px',
    backgroundColor: 'rgba(44, 42, 41, 0.9)',
    padding: '10px',
    borderRadius: '15px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
  },
  inventoryTitle: {
    color: '#8c7ae6',
    textAlign: 'center',
    marginBottom: '10px',
    fontSize: '24px',
    fontWeight: 'bold',
  },
  inventoryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '5px',
  },
  inventorySlot: {
    width: '50px',
    height: '50px',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    position: 'relative',
    transition: 'background-color 0.3s ease, transform 0.3s ease',
    borderRadius: '8px',
  },
  inventorySlotHover: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    transform: 'scale(1.05)',
  },
  hotbarSlots: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '10px',
    borderTop: '2px solid #8c7ae6',
    paddingTop: '10px',
  },
  itemTooltip: {
    position: 'absolute',
    zIndex: 1_000,
    top: '0',
    right: '0',
    transform: 'translateX(100%) translateY(-100%)',
    padding: '8px 12px',
    borderRadius: '6px',
    backgroundColor: 'rgba(21, 32, 43, 0.9)',
    color: 'rgba(255, 255, 255, 0.95)',
    fontSize: '0.875rem',
    lineHeight: '1.4',
    pointerEvents: 'none',
    whiteSpace: 'nowrap',
    boxShadow:
      '0px 0px 10px rgba(0, 0, 0, 0.5), 0px 20px 20px rgba(0, 0, 0, 0.25)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    transition: 'opacity 0.2s ease-out',
    opacity: 0,
  },
}
